version: '3'

services:
  pm-lightspeed:
    container_name: pm-lightspeed-test
    restart: on-failure
    build: .
    ports:
      - '3000:3000'
    links:
      - redis
      - mongo
    environment:
      APP_NAME: PMLightSpeed
      APP_ENV: local
      PORT: 3000
      APP_URL: http://pm-lightspeed-test:3000
      SALT_ROUND: 10
      TOKEN_SECRET: RanDomNu3b3r
      SESSION_SECRET: RanDomNu3b3r
      TOKEN_LIFESPAN: 259200000
      REDIS_URL: redis://pm-lightspeed-redis/4
      DB_URL: mongodb://pm-lightspeed-mongo/pmlightspeed
  mongo:
    container_name: pm-lightspeed-mongo
    image: 'mongo:4'
  redis:
    container_name: pm-lightspeed-redis
    image: 'redis:4.0.11'
